In [1]:
import matplotlib as plt
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [2]:
df = pd.read_csv("C:\\Users\\haier\\Downloads\\country_wise_latest.csv")

In [3]:
file = pd.read_csv("C:\\Users\\haier\\Downloads\\archive_(1)\\Admission_Data.csv")
df = pd.DataFrame(file)
df.shape

(23, 18)

In [4]:
df.sort_values('Rank',inplace=True)

In [5]:
df['S_no'] = np.arange(1,24,1)

In [6]:
pd.DataFrame(file,columns=['Name of University', 'Rigor', 'Rank', 'GPA', 'Test Score', 'Essay',
       'Recommendation', 'Interview', 'Extracurricular', 'Talent',
       'Personality', 'First Generation', 'Religious', 'State Residency',
       'Race', 'Volunteer', 'Work Experience', 'Level of Interest','S_no' ])

,Name of University,Rigor,Rank,GPA,Test Score,Essay,Recommendation,Interview,Extracurricular,Talent,Personality,First Generation,Religious,State Residency,Race,Volunteer,Work Experience,Level of Interest,S_no
0,Princeton University,3,3,3,3,3,3,1,3,3,3,1,0.0,0,1,1,1,0,NaN
1,Brown University,3,3,3,3,3,3,1,2,3,3,1,0.0,1,1,1,1,0,NaN
2,California Institute of Technology (Caltech),3,2,2,3,3,3,0,2,1,3,1,0.0,0,1,1,1,0,NaN
3,Cornell University,3,2,3,3,3,3,1,3,3,3,1,NaN,1,1,1,1,0,NaN
4,Dartmouth College,3,3,3,3,3,3,1,3,2,3,0,1.0,0,1,1,1,1,NaN
5,Harvard University,1,1,1,1,1,1,1,1,1,1,1,0.0,0,1,1,1,0,NaN
6,Massachusetts Institute of Technology (MIT),2,1,2,2,2,2,2,2,2,1,1,0.0,0,1,1,1,0,NaN
7,Stanford University,3,3,3,3,3,3,1,3,3,3,1,0.0,0,1,1,1,0,NaN
8,University of Pennsylvania,3,2,1,1,1,1,2,2,2,3,1,0.0,1,1,1,1,1,NaN
9,Washington University in St. Louis (WashU),3,3,3,3,3,3,1,2,3,3,1,0.0,0,1,2,2,1,NaN
10,Yale University,3,3,3,1,3,3,1,3,3,3,1,0.0,1,1,1,1,0,NaN
11,Rice University,3,3,3,3,3,3,1,3,3,3,1,0.0,1,1,1,1,1,NaN
12,Duke University,3,3,3,3,3,3,1,3,3,3,1,1.0,1,1,1,1,1,NaN
13,Vanderbilt University,3,3,3,3,3,2,1,3,1,3,1,0.0,1,1,1,1,0,NaN
14,Northwestern University,3,3,3,1,2,2,1,2,2,2,1,0.0,0,1,1,1,1,NaN
15,University of Southern California (USC),3,0,3,3,3,3,0,2,2,2,1,0.0,0,1,1,1,0,NaN
16,University of Notre Dame,3,2,2,1,2,2,0,2,2,3,2,1.0,0,2,2,1,1,NaN
17,Carnegie Mellon University (CMU),3,3,3,2,2,2,0,1,2,2,2,0.0,0,2,3,3,0,NaN
18,Georgetown University,3,3,3,3,3,3,2,2,3,3,1,0.0,1,1,1,1,0,NaN
19,New York University (NYU),3,3,3,3,2,2,1,2,3,2,1,0.0,0,1,1,1,1,NaN
20,The Ohio State University (OSU),3,3,3,2,1,1,0,2,2,1,2,0.0,1,1,2,2,0,NaN
21,Miami University,3,3,3,3,3,3,0,1,3,3,1,1.0,1,0,1,1,0,NaN
22,Case Western Reserve University (CWR),3,3,3,1,2,2,2,1,2,2,1,0.0,0,2,2,1,1,NaN

In [7]:
grope_by = df.groupby('Name of University')
grope_by

In [8]:
for Name_of_University ,  Name_of_University_df in grope_by:
    print(Name_of_University)
    print(Name_of_University_df)

Brown University
  Name of University  Rigor  Rank  GPA  Test Score  Essay  Recommendation  \
1   Brown University      3     3    3           3      3               3

   Interview  Extracurricular  Talent  Personality  First Generation  \
1          1                2       3            3                 1

   Religious  State Residency  Race  Volunteer  Work Experience  \
1        0.0                1     1          1                1

   Level of Interest  S_no
1                  0    21
California Institute of Technology (Caltech)
                             Name of University  Rigor  Rank  GPA  Test Score  \
2  California Institute of Technology (Caltech)      3     2    2           3

   Essay  Recommendation  Interview  Extracurricular  Talent  Personality  \
2      3               3          0                2       1            3

   First Generation  Religious  State Residency  Race  Volunteer  \
2                 1        0.0                0     1          1

   Work Experience  Level of Interest  S_no
2                1                  0     4
Carnegie Mellon University (CMU)
                  Name of University  Rigor  Rank  GPA  Test Score  Essay  \
17  Carnegie Mellon University (CMU)      3     3    3           2      2

    Recommendation  Interview  Extracurricular  Talent  Personality  \
17               2          0                1       2            2

    First Generation  Religious  State Residency  Race  Volunteer  \
17                 2        0.0                0     2          3

    Work Experience  Level of Interest  S_no
17                3                  0    12
Case Western Reserve University (CWR)
                       Name of University  Rigor  Rank  GPA  Test Score  \
22  Case Western Reserve University (CWR)      3     3    3           1

    Essay  Recommendation  Interview  Extracurricular  Talent  Personality  \
22      2               2          2                1       2            2

    First Generation  Religious  State Residency  Race  Volunteer  \
22                 1        0.0                0     2          2

    Work Experience  Level of Interest  S_no
22                1                  1    23
Cornell University
   Name of University  Rigor  Rank  GPA  Test Score  Essay  Recommendation  \
3  Cornell University      3     2    3           3      3               3

   Interview  Extracurricular  Talent  Personality  First Generation  \
3          1                3       3            3                 1

   Religious  State Residency  Race  Volunteer  Work Experience  \
3        NaN                1     1          1                1

   Level of Interest  S_no
3                  0     5
Dartmouth College
  Name of University  Rigor  Rank  GPA  Test Score  Essay  Recommendation  \
4  Dartmouth College      3     3    3           3      3               3

   Interview  Extracurricular  Talent  Personality  First Generation  \
4          1                3       2            3                 0

   Religious  State Residency  Race  Volunteer  Work Experience  \
4        1.0                0     1          1                1

   Level of Interest  S_no
4                  1    20
Duke University
   Name of University  Rigor  Rank  GPA  Test Score  Essay  Recommendation  \
12    Duke University      3     3    3           3      3               3

    Interview  Extracurricular  Talent  Personality  First Generation  \
12          1                3       3            3                 1

    Religious  State Residency  Race  Volunteer  Work Experience  \
12        1.0                1     1          1                1

    Level of Interest  S_no
12                  1    15
Georgetown University
       Name of University  Rigor  Rank  GPA  Test Score  Essay  \
18  Georgetown University      3     3    3           3      3

    Recommendation  Interview  Extracurricular  Talent  Personality  \
18               3          2                2       3            3

    First Generation  Religious  State Residency  Race  Volunteer  \
18                 1        0.0                1     1          1

    Work Experience  Level of Interest  S_no
18                1                  0    11
Harvard University
   Name of University  Rigor  Rank  GPA  Test Score  Essay  Recommendation  \
5  Harvard University      1     1    1           1      1               1

   Interview  Extracurricular  Talent  Personality  First Generation  \
5          1                1       1            1                 1

   Religious  State Residency  Race  Volunteer  Work Experience  \
5        0.0                0     1          1                1

   Level of Interest  S_no
5                  0     2
Massachusetts Institute of Technology (MIT)
                            Name of University  Rigor  Rank  GPA  Test Score  \
6  Massachusetts Institute of Technology (MIT)      2     1    2           2

   Essay  Recommendation  Interview  Extracurricular  Talent  Personality  \
6      2               2          2                2       2            1

   First Generation  Religious  State Residency  Race  Volunteer  \
6                 1        0.0                0     1          1

   Work Experience  Level of Interest  S_no
6                1                  0     3
Miami University
   Name of University  Rigor  Rank  GPA  Test Score  Essay  Recommendation  \
21   Miami University      3     3    3           3      3               3

    Interview  Extracurricular  Talent  Personality  First Generation  \
21          0                1       3            3                 1

    Religious  State Residency  Race  Volunteer  Work Experience  \
21        1.0                1     0          1                1

    Level of Interest  S_no
21                  0    16
New York University (NYU)
           Name of University  Rigor  Rank  GPA  Test Score  Essay  \
19  New York University (NYU)      3     3    3           3      2

    Recommendation  Interview  Extracurricular  Talent  Personality  \
19               2          1                2       3            2

    First Generation  Religious  State Residency  Race  Volunteer  \
19                 1        0.0                0     1          1

    Work Experience  Level of Interest  S_no
19                1                  1    10
Northwestern University
         Name of University  Rigor  Rank  GPA  Test Score  Essay  \
14  Northwestern University      3     3    3           1      2

    Recommendation  Interview  Extracurricular  Talent  Personality  \
14               2          1                2       2            2

    First Generation  Religious  State Residency  Race  Volunteer  \
14                 1        0.0                0     1          1

    Work Experience  Level of Interest  S_no
14                1                  1    13
Princeton University
     Name of University  Rigor  Rank  GPA  Test Score  Essay  Recommendation  \
0  Princeton University      3     3    3           3      3               3

   Interview  Extracurricular  Talent  Personality  First Generation  \
0          1                3       3            3                 1

   Religious  State Residency  Race  Volunteer  Work Experience  \
0        0.0                0     1          1                1

   Level of Interest  S_no
0                  0     8
Rice University
   Name of University  Rigor  Rank  GPA  Test Score  Essay  Recommendation  \
11    Rice University      3     3    3           3      3               3

    Interview  Extracurricular  Talent  Personality  First Generation  \
11          1                3       3            3                 1

    Religious  State Residency  Race  Volunteer  Work Experience  \
11        0.0                1     1          1                1

    Level of Interest  S_no
11                  1    14
Stanford University
    Name of University  Rigor  Rank  GPA  Test Score  Essay  Recommendation  \
7  Stanford University      3     3    3           3      3               3

   Interview  Extracurricular  Talent  Personality  First Generation  \
7          1                3       3            3                 1

   Religious  State Residency  Race  Volunteer  Work Experience  \
7        0.0                0     1          1                1

   Level of Interest  S_no
7                  0    19
The Ohio State University (OSU)
                 Name of University  Rigor  Rank  GPA  Test Score  Essay  \
20  The Ohio State University (OSU)      3     3    3           2      1

    Recommendation  Interview  Extracurricular  Talent  Personality  \
20               1          0                2       2            1

    First Generation  Religious  State Residency  Race  Volunteer  \
20                 2        0.0                1     1          2

    Work Experience  Level of Interest  S_no
20                2                  0     9
University of Notre Dame
          Name of University  Rigor  Rank  GPA  Test Score  Essay  \
16  University of Notre Dame      3     2    2           1      2

    Recommendation  Interview  Extracurricular  Talent  Personality  \
16               2          0                2       2            3

    First Generation  Religious  State Residency  Race  Volunteer  \
16                 2        1.0                0     2          2

    Work Experience  Level of Interest  S_no
16                1                  1     7
University of Pennsylvania
           Name of University  Rigor  Rank  GPA  Test Score  Essay  \
8  University of Pennsylvania      3     2    1           1      1

   Recommendation  Interview  Extracurricular  Talent  Personality  \
8               1          2                2       2            3

   First Generation  Religious  State Residency  Race  Volunteer  \
8                 1        0.0                1     1          1

   Work Experience  Level of Interest  S_no
8                1                  1     6
University of Southern California (USC)
                         Name of University  Rigor  Rank  GPA  Test Score  \
15  University of Southern California (USC)      3     0    3           3

    Essay  Recommendation  Interview  Extracurricular  Talent  Personality  \
15      3               3          0                2       2            2

    First Generation  Religious  State Residency  Race  Volunteer  \
15                 1        0.0                0     1          1

    Work Experience  Level of Interest  S_no
15                1                  0     1
Vanderbilt University
       Name of University  Rigor  Rank  GPA  Test Score  Essay  \
13  Vanderbilt University      3     3    3           3      3

    Recommendation  Interview  Extracurricular  Talent  Personality  \
13               2          1                3       1            3

    First Generation  Religious  State Residency  Race  Volunteer  \
13                 1        0.0                1     1          1

    Work Experience  Level of Interest  S_no
13                1                  0    22
Washington University in St. Louis (WashU)
                           Name of University  Rigor  Rank  GPA  Test Score  \
9  Washington University in St. Louis (WashU)      3     3    3           3

   Essay  Recommendation  Interview  Extracurricular  Talent  Personality  \
9      3               3          1                2       3            3

   First Generation  Religious  State Residency  Race  Volunteer  \
9                 1        0.0                0     1          2

   Work Experience  Level of Interest  S_no
9                2                  1    18
Yale University
   Name of University  Rigor  Rank  GPA  Test Score  Essay  Recommendation  \
10    Yale University      3     3    3           1      3               3

    Interview  Extracurricular  Talent  Personality  First Generation  \
10          1                3       3            3                 1

    Religious  State Residency  Race  Volunteer  Work Experience  \
10        0.0                1     1          1                1

    Level of Interest  S_no
10                  0    17

In [9]:
grope_by.get_group('Brown University')

,Name of University,Rigor,Rank,GPA,Test Score,Essay,Recommendation,Interview,Extracurricular,Talent,Personality,First Generation,Religious,State Residency,Race,Volunteer,Work Experience,Level of Interest,S_no
1,Brown University,3,3,3,3,3,3,1,2,3,3,1,0.0,1,1,1,1,0,21

In [10]:
df.set_index('S_no',inplace=True)

In [11]:
df.fillna(0,inplace=True) #by inplace argument the zero value becomes perment for overall dataset

In [12]:
df['S_no'] = np.arange(1,24,1)

In [13]:
df.loc[:,'Religious']=df.loc[:,'Religious'].apply(pd.to_numeric).astype('int64')

df.info()

In [14]:
df.sort_values(by='Rank' , inplace=True)

In [15]:
#df.sort_index(axis=0)

In [16]:
#df.sort_index(axis=1)

In [17]:
S_no = np.arange(1,24,1)

pd.DataFrame(file,columns=['Name of University', 'Rigor', 'Rank', 'GPA', 'Test Score', 'Essay',
       'Recommendation', 'Interview', 'Extracurricular', 'Talent',
       'Personality', 'First Generation', 'Religious', 'State Residency',
       'Race', 'Volunteer', 'Work Experience', 'Level of Interest','sum_of_experience_and_interest','S_no' ],index=[12,5,22])

In [18]:
#df.set_index('Rank')

In [19]:
#df.sort_values(by=['Rank','Name of University'])

df.index = S_no
S_no

df.index

df.count()

df.sum() # it gives the total sum of all values of each column

df.sum(axis=1) # Passing axis=1 sums over the rows instead:

df.mean(axis=1, skipna=False)

df[df['Rank']==1]

df[df['Rank']==2]

df[df['Rank']==3]

df.describe()

df.columns

df.shape

df.index

In [20]:
'Race' in df

True

df.isnull()

df['Name of University']

df.ix[22]

In [21]:
df['sum_of_experience_and_interest'] = df['Work Experience'] + df['Level of Interest']

In [22]:
df['S_no'] = np.arange(1,24,1)

df

df.index

df.style.hidden_index()

df

pd.DataFrame(file,columns=['Name of University', 'Rigor', 'Rank', 'GPA', 'Test Score', 'Essay',
       'Recommendation', 'Interview', 'Extracurricular', 'Talent',
       'Personality', 'First Generation', 'Religious', 'State Residency',
       'Race', 'Volunteer', 'Work Experience', 'Level of Interest','sum_of_experience_and_interest'],index=[12,5,22])

df_1 = pd.DataFrame(file,columns=['Religious', 'Rigor', 'Rank', 'GPA', 'Test Score', 'Essay',
       'Recommendation', 'Interview', 'Extracurricular', 'Talent',
       'Personality', 'First Generation', 'Name of University', 'State Residency',
       'Race', 'Volunteer', 'Work Experience', 'Level of Interest','sum_of_experience_and_interest'],index=[1,13,4])

df_1

pd.DataFrame(file,columns=['Religious', 'Rigor', 'Rank', 'GPA', 'Test Score', 'Essay',
       'Recommendation', 'Interview', 'Extracurricular', 'Talent',
       'Personality', 'First Generation', 'Name of University', 'State Residency',
       'Race', 'Volunteer', 'Work Experience', 'Level of Interest'])

In [23]:
covid = pd.read_csv("C:\\Users\\haier\\Downloads\\country_wise_latest.csv")
part_covid = covid.head(15)
part_covid

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,Andorra,907,52,803,52,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,950,41,242,667,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa
5,Antigua and Barbuda,86,3,65,18,4,0,5,3.49,75.58,4.62,76,10,13.16,Americas
6,Argentina,167416,3059,72575,91782,4890,120,2057,1.83,43.35,4.21,130774,36642,28.02,Americas
7,Armenia,37390,711,26665,10014,73,6,187,1.90,71.32,2.67,34981,2409,6.89,Europe
8,Australia,15303,167,9311,5825,368,6,137,1.09,60.84,1.79,12428,2875,23.13,Western Pacific
9,Austria,20558,713,18246,1599,86,1,37,3.47,88.75,3.91,19743,815,4.13,Europe
10,Azerbaijan,30446,423,23242,6781,396,6,558,1.39,76.34,1.82,27890,2556,9.16,Europe
11,Bahamas,382,11,91,280,40,0,0,2.88,23.82,12.09,174,208,119.54,Americas
12,Bahrain,39482,141,36110,3231,351,1,421,0.36,91.46,0.39,36936,2546,6.89,Eastern Mediterranean
13,Bangladesh,226225,2965,125683,97577,2772,37,1801,1.31,55.56,2.36,207453,18772,9.05,South-East Asia
14,Barbados,110,7,94,9,0,0,0,6.36,85.45,7.45,106,4,3.77,Americas

In [24]:
part_covid.sort_values(by=['Confirmed','Country/Region'])#Country/Region base on confirmed
#rows are sorted on basee of their column names

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
5,Antigua and Barbuda,86,3,65,18,4,0,5,3.49,75.58,4.62,76,10,13.16,Americas
14,Barbados,110,7,94,9,0,0,0,6.36,85.45,7.45,106,4,3.77,Americas
11,Bahamas,382,11,91,280,40,0,0,2.88,23.82,12.09,174,208,119.54,Americas
3,Andorra,907,52,803,52,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,950,41,242,667,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
8,Australia,15303,167,9311,5825,368,6,137,1.09,60.84,1.79,12428,2875,23.13,Western Pacific
9,Austria,20558,713,18246,1599,86,1,37,3.47,88.75,3.91,19743,815,4.13,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
10,Azerbaijan,30446,423,23242,6781,396,6,558,1.39,76.34,1.82,27890,2556,9.16,Europe
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
7,Armenia,37390,711,26665,10014,73,6,187,1.90,71.32,2.67,34981,2409,6.89,Europe
12,Bahrain,39482,141,36110,3231,351,1,421,0.36,91.46,0.39,36936,2546,6.89,Eastern Mediterranean
6,Argentina,167416,3059,72575,91782,4890,120,2057,1.83,43.35,4.21,130774,36642,28.02,Americas
13,Bangladesh,226225,2965,125683,97577,2772,37,1801,1.31,55.56,2.36,207453,18772,9.05,South-East Asia

In [25]:
part_covid.sort_values(by=['Confirmed','Country/Region'],ascending=False)#Country/Region base on confirmed
#rows are sorted on bases of their column names,by default it in ascending order

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
13,Bangladesh,226225,2965,125683,97577,2772,37,1801,1.31,55.56,2.36,207453,18772,9.05,South-East Asia
6,Argentina,167416,3059,72575,91782,4890,120,2057,1.83,43.35,4.21,130774,36642,28.02,Americas
12,Bahrain,39482,141,36110,3231,351,1,421,0.36,91.46,0.39,36936,2546,6.89,Eastern Mediterranean
7,Armenia,37390,711,26665,10014,73,6,187,1.90,71.32,2.67,34981,2409,6.89,Europe
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
10,Azerbaijan,30446,423,23242,6781,396,6,558,1.39,76.34,1.82,27890,2556,9.16,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
9,Austria,20558,713,18246,1599,86,1,37,3.47,88.75,3.91,19743,815,4.13,Europe
8,Australia,15303,167,9311,5825,368,6,137,1.09,60.84,1.79,12428,2875,23.13,Western Pacific
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
4,Angola,950,41,242,667,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa
3,Andorra,907,52,803,52,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
11,Bahamas,382,11,91,280,40,0,0,2.88,23.82,12.09,174,208,119.54,Americas
14,Barbados,110,7,94,9,0,0,0,6.36,85.45,7.45,106,4,3.77,Americas
5,Antigua and Barbuda,86,3,65,18,4,0,5,3.49,75.58,4.62,76,10,13.16,Americas

In [26]:
part_covid.sort_index(axis=1)#axis= 1 represents columns and all colunms nAmes are sorted by default it in ascending order

,1 week % increase,1 week change,Active,Confirmed,Confirmed last week,Country/Region,Deaths,Deaths / 100 Cases,Deaths / 100 Recovered,New cases,New deaths,New recovered,Recovered,Recovered / 100 Cases,WHO Region
0,2.07,737,9796,36263,35526,Afghanistan,1269,3.50,5.04,106,10,18,25198,69.49,Eastern Mediterranean
1,17.00,709,1991,4880,4171,Albania,144,2.95,5.25,117,6,63,2745,56.25,Europe
2,18.07,4282,7973,27973,23691,Algeria,1163,4.16,6.17,616,8,749,18837,67.34,Africa
3,2.60,23,52,907,884,Andorra,52,5.73,6.48,10,0,0,803,88.53,Europe
4,26.84,201,667,950,749,Angola,41,4.32,16.94,18,1,0,242,25.47,Africa
5,13.16,10,18,86,76,Antigua and Barbuda,3,3.49,4.62,4,0,5,65,75.58,Americas
6,28.02,36642,91782,167416,130774,Argentina,3059,1.83,4.21,4890,120,2057,72575,43.35,Americas
7,6.89,2409,10014,37390,34981,Armenia,711,1.90,2.67,73,6,187,26665,71.32,Europe
8,23.13,2875,5825,15303,12428,Australia,167,1.09,1.79,368,6,137,9311,60.84,Western Pacific
9,4.13,815,1599,20558,19743,Austria,713,3.47,3.91,86,1,37,18246,88.75,Europe
10,9.16,2556,6781,30446,27890,Azerbaijan,423,1.39,1.82,396,6,558,23242,76.34,Europe
11,119.54,208,280,382,174,Bahamas,11,2.88,12.09,40,0,0,91,23.82,Americas
12,6.89,2546,3231,39482,36936,Bahrain,141,0.36,0.39,351,1,421,36110,91.46,Eastern Mediterranean
13,9.05,18772,97577,226225,207453,Bangladesh,2965,1.31,2.36,2772,37,1801,125683,55.56,South-East Asia
14,3.77,4,9,110,106,Barbados,7,6.36,7.45,0,0,0,94,85.45,Americas

In [27]:
part_covid.sort_index(axis=1,ascending=False)#axis= 1 represents columns and all colunms nAmes are sorted by default it in ascending order

,WHO Region,Recovered / 100 Cases,Recovered,New recovered,New deaths,New cases,Deaths / 100 Recovered,Deaths / 100 Cases,Deaths,Country/Region,Confirmed last week,Confirmed,Active,1 week change,1 week % increase
0,Eastern Mediterranean,69.49,25198,18,10,106,5.04,3.50,1269,Afghanistan,35526,36263,9796,737,2.07
1,Europe,56.25,2745,63,6,117,5.25,2.95,144,Albania,4171,4880,1991,709,17.00
2,Africa,67.34,18837,749,8,616,6.17,4.16,1163,Algeria,23691,27973,7973,4282,18.07
3,Europe,88.53,803,0,0,10,6.48,5.73,52,Andorra,884,907,52,23,2.60
4,Africa,25.47,242,0,1,18,16.94,4.32,41,Angola,749,950,667,201,26.84
5,Americas,75.58,65,5,0,4,4.62,3.49,3,Antigua and Barbuda,76,86,18,10,13.16
6,Americas,43.35,72575,2057,120,4890,4.21,1.83,3059,Argentina,130774,167416,91782,36642,28.02
7,Europe,71.32,26665,187,6,73,2.67,1.90,711,Armenia,34981,37390,10014,2409,6.89
8,Western Pacific,60.84,9311,137,6,368,1.79,1.09,167,Australia,12428,15303,5825,2875,23.13
9,Europe,88.75,18246,37,1,86,3.91,3.47,713,Austria,19743,20558,1599,815,4.13
10,Europe,76.34,23242,558,6,396,1.82,1.39,423,Azerbaijan,27890,30446,6781,2556,9.16
11,Americas,23.82,91,0,0,40,12.09,2.88,11,Bahamas,174,382,280,208,119.54
12,Eastern Mediterranean,91.46,36110,421,1,351,0.39,0.36,141,Bahrain,36936,39482,3231,2546,6.89
13,South-East Asia,55.56,125683,1801,37,2772,2.36,1.31,2965,Bangladesh,207453,226225,97577,18772,9.05
14,Americas,85.45,94,0,0,0,7.45,6.36,7,Barbados,106,110,9,4,3.77

In [28]:
covid = pd.read_csv("C:\\Users\\haier\\Downloads\\country_wise_latest.csv")
covid

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,Andorra,907,52,803,52,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,950,41,242,667,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,West Bank and Gaza,10621,78,3752,6791,152,2,0,0.73,35.33,2.08,8916,1705,19.12,Eastern Mediterranean
183,Western Sahara,10,1,8,1,0,0,0,10.00,80.00,12.50,10,0,0.00,Africa
184,Yemen,1691,483,833,375,10,4,36,28.56,49.26,57.98,1619,72,4.45,Eastern Mediterranean
185,Zambia,4552,140,2815,1597,71,1,465,3.08,61.84,4.97,3326,1226,36.86,Africa
186,Zimbabwe,2704,36,542,2126,192,2,24,1.33,20.04,6.64,1713,991,57.85,Africa

In [29]:
for i in covid.iterrows():
    print(i)

(0, Country/Region                      Afghanistan
Confirmed                                 36263
Deaths                                     1269
Recovered                                 25198
Active                                     9796
New cases                                   106
New deaths                                   10
New recovered                                18
Deaths / 100 Cases                          3.5
Recovered / 100 Cases                     69.49
Deaths / 100 Recovered                     5.04
Confirmed last week                       35526
1 week change                               737
1 week % increase                          2.07
WHO Region                Eastern Mediterranean
Name: 0, dtype: object)
(1, Country/Region            Albania
Confirmed                    4880
Deaths                        144
Recovered                    2745
Active                       1991
New cases                     117
New deaths                      6
New recovered                  63
Deaths / 100 Cases           2.95
Recovered / 100 Cases       56.25
Deaths / 100 Recovered       5.25
Confirmed last week          4171
1 week change                 709
1 week % increase              17
WHO Region                 Europe
Name: 1, dtype: object)
(2, Country/Region            Algeria
Confirmed                   27973
Deaths                       1163
Recovered                   18837
Active                       7973
New cases                     616
New deaths                      8
New recovered                 749
Deaths / 100 Cases           4.16
Recovered / 100 Cases       67.34
Deaths / 100 Recovered       6.17
Confirmed last week         23691
1 week change                4282
1 week % increase           18.07
WHO Region                 Africa
Name: 2, dtype: object)
(3, Country/Region            Andorra
Confirmed                     907
Deaths                         52
Recovered                     803
Active                         52
New cases                      10
New deaths                      0
New recovered                   0
Deaths / 100 Cases           5.73
Recovered / 100 Cases       88.53
Deaths / 100 Recovered       6.48
Confirmed last week           884
1 week change                  23
1 week % increase             2.6
WHO Region                 Europe
Name: 3, dtype: object)
(4, Country/Region            Angola
Confirmed                    950
Deaths                        41
Recovered                    242
Active                       667
New cases                     18
New deaths                     1
New recovered                  0
Deaths / 100 Cases          4.32
Recovered / 100 Cases      25.47
Deaths / 100 Recovered     16.94
Confirmed last week          749
1 week change                201
1 week % increase          26.84
WHO Region                Africa
Name: 4, dtype: object)
(5, Country/Region            Antigua and Barbuda
Confirmed                                  86
Deaths                                      3
Recovered                                  65
Active                                     18
New cases                                   4
New deaths                                  0
New recovered                               5
Deaths / 100 Cases                       3.49
Recovered / 100 Cases                   75.58
Deaths / 100 Recovered                   4.62
Confirmed last week                        76
1 week change                              10
1 week % increase                       13.16
WHO Region                           Americas
Name: 5, dtype: object)
(6, Country/Region            Argentina
Confirmed                    167416
Deaths                         3059
Recovered                     72575
Active                        91782
New cases                      4890
New deaths                      120
New recovered                  2057
Deaths / 100 Cases             1.83
Recovered / 100 Cases         43.35
Deaths / 100 Recovered         4.21
Confirmed last week          130774
1 week change                 36642
1 week % increase             28.02
WHO Region                 Americas
Name: 6, dtype: object)
(7, Country/Region            Armenia
Confirmed                   37390
Deaths                        711
Recovered                   26665
Active                      10014
New cases                      73
New deaths                      6
New recovered                 187
Deaths / 100 Cases            1.9
Recovered / 100 Cases       71.32
Deaths / 100 Recovered       2.67
Confirmed last week         34981
1 week change                2409
1 week % increase            6.89
WHO Region                 Europe
Name: 7, dtype: object)
(8, Country/Region                  Australia
Confirmed                           15303
Deaths                                167
Recovered                            9311
Active                               5825
New cases                             368
New deaths                              6
New recovered                         137
Deaths / 100 Cases                   1.09
Recovered / 100 Cases               60.84
Deaths / 100 Recovered               1.79
Confirmed last week                 12428
1 week change                        2875
1 week % increase                   23.13
WHO Region                Western Pacific
Name: 8, dtype: object)
(9, Country/Region            Austria
Confirmed                   20558
Deaths                        713
Recovered                   18246
Active                       1599
New cases                      86
New deaths                      1
New recovered                  37
Deaths / 100 Cases           3.47
Recovered / 100 Cases       88.75
Deaths / 100 Recovered       3.91
Confirmed last week         19743
1 week change                 815
1 week % increase            4.13
WHO Region                 Europe
Name: 9, dtype: object)
(10, Country/Region            Azerbaijan
Confirmed                      30446
Deaths                           423
Recovered                      23242
Active                          6781
New cases                        396
New deaths                         6
New recovered                    558
Deaths / 100 Cases              1.39
Recovered / 100 Cases          76.34
Deaths / 100 Recovered          1.82
Confirmed last week            27890
1 week change                   2556
1 week % increase               9.16
WHO Region                    Europe
Name: 10, dtype: object)
(11, Country/Region             Bahamas
Confirmed                      382
Deaths                          11
Recovered                       91
Active                         280
New cases                       40
New deaths                       0
New recovered                    0
Deaths / 100 Cases            2.88
Recovered / 100 Cases        23.82
Deaths / 100 Recovered       12.09
Confirmed last week            174
1 week change                  208
1 week % increase           119.54
WHO Region                Americas
Name: 11, dtype: object)
(12, Country/Region                          Bahrain
Confirmed                                 39482
Deaths                                      141
Recovered                                 36110
Active                                     3231
New cases                                   351
New deaths                                    1
New recovered                               421
Deaths / 100 Cases                         0.36
Recovered / 100 Cases                     91.46
Deaths / 100 Recovered                     0.39
Confirmed last week                       36936
1 week change                              2546
1 week % increase                          6.89
WHO Region                Eastern Mediterranean
Name: 12, dtype: object)
(13, Country/Region                 Bangladesh
Confirmed                          226225
Deaths                               2965
Recovered                          125683
Active                              97577
New cases                            2772
New deaths                             37
New recovered                        1801
Deaths / 100 Cases                   1.31
Recovered / 100 Cases               55.56
Deaths / 100 Recovered               2.36
Confirmed last week                207453
1 week change                       18772
1 week % increase                    9.05
WHO Region                South-East Asia
Name: 13, dtype: object)
(14, Country/Region            Barbados
Confirmed                      110
Deaths                           7
Recovered                       94
Active                           9
New cases                        0
New deaths                       0
New recovered                    0
Deaths / 100 Cases            6.36
Recovered / 100 Cases        85.45
Deaths / 100 Recovered        7.45
Confirmed last week            106
1 week change                    4
1 week % increase             3.77
WHO Region                Americas
Name: 14, dtype: object)
(15, Country/Region            Belarus
Confirmed                   67251
Deaths                        538
Recovered                   60492
Active                       6221
New cases                     119
New deaths                      4
New recovered                  67
Deaths / 100 Cases            0.8
Recovered / 100 Cases       89.95
Deaths / 100 Recovered       0.89
Confirmed last week         66213
1 week change                1038
1 week % increase            1.57
WHO Region                 Europe
Name: 15, dtype: object)
(16, Country/Region            Belgium
Confirmed                   66428
Deaths                       9822
Recovered                   17452
Active                      39154
New cases                     402
New deaths                      1
New recovered                  14
Deaths / 100 Cases          14.79
Recovered / 100 Cases       26.27
Deaths / 100 Recovered      56.28
Confirmed last week         64094
1 week change                2334
1 week % increase            3.64
WHO Region                 Europe
Name: 16, dtype: object)
(17, Country/Region              Belize
Confirmed                       48
Deaths                           2
Recovered                       26
Active                          20
New cases                        0
New deaths                       0
New recovered                    0
Deaths / 100 Cases            4.17
Recovered / 100 Cases        54.17
Deaths / 100 Recovered        7.69
Confirmed last week             40
1 week change                    8
1 week % increase               20
WHO Region                Americas
Name: 17, dtype: object)
(18, Country/Region             Benin
Confirmed                   1770
Deaths                        35
Recovered                   1036
Active                       699
New cases                      0
New deaths                     0
New recovered                  0
Deaths / 100 Cases          1.98
Recovered / 100 Cases      58.53
Deaths / 100 Recovered      3.38
Confirmed last week         1602
1 week change                168
1 week % increase          10.49
WHO Region                Africa
Name: 18, dtype: object)
(19, Country/Region                     Bhutan
Confirmed                              99
Deaths                                  0
Recovered                              86
Active                                 13
New cases                               4
New deaths                              0
New recovered                           1
Deaths / 100 Cases                      0
Recovered / 100 Cases               86.87
Deaths / 100 Recovered                  0
Confirmed last week                    90
1 week change                           9
1 week % increase                      10
WHO Region                South-East Asia
Name: 19, dtype: object)
(20, Country/Region             Bolivia
Confirmed                    71181
Deaths                        2647
Recovered                    21478
Active                       47056
New cases                     1752
New deaths                      64
New recovered                  309
Deaths / 100 Cases            3.72
Recovered / 100 Cases        30.17
Deaths / 100 Recovered       12.32
Confirmed last week          60991
1 week change                10190
1 week % increase            16.71
WHO Region                Americas
Name: 20, dtype: object)
(21, Country/Region            Bosnia and Herzegovina
Confirmed                                  10498
Deaths                                       294
Recovered                                   4930
Active                                      5274
New cases                                    731
New deaths                                    14
New recovered                                375
Deaths / 100 Cases                           2.8
Recovered / 100 Cases                      46.96
Deaths / 100 Recovered                      5.96
Confirmed last week                         8479
1 week change                               2019
1 week % increase                          23.81
WHO Region                                Europe
Name: 21, dtype: object)
(22, Country/Region            Botswana
Confirmed                      739
Deaths                           2
Recovered                       63
Active                         674
New cases                       53
New deaths                       1
New recovered                   11
Deaths / 100 Cases            0.27
Recovered / 100 Cases         8.53
Deaths / 100 Recovered        3.17
Confirmed last week            522
1 week change                  217
1 week % increase            41.57
WHO Region                  Africa
Name: 22, dtype: object)
(23, Country/Region              Brazil
Confirmed                  2442375
Deaths                       87618
Recovered                  1846641
Active                      508116
New cases                    23284
New deaths                     614
New recovered                33728
Deaths / 100 Cases            3.59
Recovered / 100 Cases        75.61
Deaths / 100 Recovered        4.74
Confirmed last week        2118646
1 week change               323729
1 week % increase            15.28
WHO Region                Americas
Name: 23, dtype: object)
(24, Country/Region                     Brunei
Confirmed                             141
Deaths                                  3
Recovered                             138
Active                                  0
New cases                               0
New deaths                              0
New recovered                           0
Deaths / 100 Cases                   2.13
Recovered / 100 Cases               97.87
Deaths / 100 Recovered               2.17
Confirmed last week                   141
1 week change                           0
1 week % increase                       0
WHO Region                Western Pacific
Name: 24, dtype: object)
(25, Country/Region            Bulgaria
Confirmed                    10621
Deaths                         347
Recovered                     5585
Active                        4689
New cases                      194
New deaths                       7
New recovered                  230
Deaths / 100 Cases            3.27
Recovered / 100 Cases        52.58
Deaths / 100 Recovered        6.21
Confirmed last week           8929
1 week change                 1692
1 week % increase            18.95
WHO Region                  Europe
Name: 25, dtype: object)
(26, Country/Region            Burkina Faso
Confirmed                         1100
Deaths                              53
Recovered                          926
Active                             121
New cases                           14
New deaths                           0
New recovered                        6
Deaths / 100 Cases                4.82
Recovered / 100 Cases            84.18
Deaths / 100 Recovered            5.72
Confirmed last week               1065
1 week change                       35
1 week % increase                 3.29
WHO Region                      Africa
Name: 26, dtype: object)
(27, Country/Region                      Burma
Confirmed                             350
Deaths                                  6
Recovered                             292
Active                                 52
New cases                               0
New deaths                              0
New recovered                           2
Deaths / 100 Cases                   1.71
Recovered / 100 Cases               83.43
Deaths / 100 Recovered               2.05
Confirmed last week                   341
1 week change                           9
1 week % increase                    2.64
WHO Region                South-East Asia
Name: 27, dtype: object)
(28, Country/Region            Burundi
Confirmed                     378
Deaths                          1
Recovered                     301
Active                         76
New cases                      17
New deaths                      0
New recovered                  22
Deaths / 100 Cases           0.26
Recovered / 100 Cases       79.63
Deaths / 100 Recovered       0.33
Confirmed last week           322
1 week change                  56
1 week % increase           17.39
WHO Region                 Africa
Name: 28, dtype: object)
(29, Country/Region            Cabo Verde
Confirmed                       2328
Deaths                            22
Recovered                       1550
Active                           756
New cases                         21
New deaths                         0
New recovered                    103
Deaths / 100 Cases              0.95
Recovered / 100 Cases          66.58
Deaths / 100 Recovered          1.42
Confirmed last week             2071
1 week change                    257
1 week % increase              12.41
WHO Region                    Africa
Name: 29, dtype: object)
(30, Country/Region                   Cambodia
Confirmed                             226
Deaths                                  0
Recovered                             147
Active                                 79
New cases                               1
New deaths                              0
New recovered                           4
Deaths / 100 Cases                      0
Recovered / 100 Cases               65.04
Deaths / 100 Recovered                  0
Confirmed last week                   171
1 week change                          55
1 week % increase                   32.16
WHO Region                Western Pacific
Name: 30, dtype: object)
(31, Country/Region            Cameroon
Confirmed                    17110
Deaths                         391
Recovered                    14539
Active                        2180
New cases                      402
New deaths                       6
New recovered                    0
Deaths / 100 Cases            2.29
Recovered / 100 Cases        84.97
Deaths / 100 Recovered        2.69
Confirmed last week          16157
1 week change                  953
1 week % increase              5.9
WHO Region                  Africa
Name: 31, dtype: object)
(32, Country/Region              Canada
Confirmed                   116458
Deaths                        8944
Recovered                        0
Active                      107514
New cases                      682
New deaths                      11
New recovered                    0
Deaths / 100 Cases            7.68
Recovered / 100 Cases            0
Deaths / 100 Recovered         inf
Confirmed last week         112925
1 week change                 3533
1 week % increase             3.13
WHO Region                Americas
Name: 32, dtype: object)
(33, Country/Region            Central African Republic
Confirmed                                     4599
Deaths                                          59
Recovered                                     1546
Active                                        2994
New cases                                        0

(156, Country/Region            South Sudan
Confirmed                        2305
Deaths                             46
Recovered                        1175
Active                           1084
New cases                          43
New deaths                          1
New recovered                       0
Deaths / 100 Cases                  2
Recovered / 100 Cases           50.98
Deaths / 100 Recovered           3.91
Confirmed last week              2211
1 week change                      94
1 week % increase                4.25
WHO Region                     Africa
Name: 156, dtype: object)
(157, Country/Region             Spain
Confirmed                 272421
Deaths                     28432
Recovered                 150376
Active                     93613
New cases                      0
New deaths                     0
New recovered                  0
Deaths / 100 Cases         10.44
Recovered / 100 Cases       55.2
Deaths / 100 Recovered     18.91
Confirmed last week       264836
1 week change               7585
1 week % increase           2.86
WHO Region                Europe
Name: 157, dtype: object)
(158, Country/Region                  Sri Lanka
Confirmed                            2805
Deaths                                 11
Recovered                            2121
Active                                673
New cases                              23
New deaths                              0
New recovered                          15
Deaths / 100 Cases                   0.39
Recovered / 100 Cases               75.61
Deaths / 100 Recovered               0.52
Confirmed last week                  2730
1 week change                          75
1 week % increase                    2.75
WHO Region                South-East Asia
Name: 158, dtype: object)
(159, Country/Region                            Sudan
Confirmed                                 11424
Deaths                                      720
Recovered                                  5939
Active                                     4765
New cases                                    39
New deaths                                    3
New recovered                                49
Deaths / 100 Cases                          6.3
Recovered / 100 Cases                     51.99
Deaths / 100 Recovered                    12.12
Confirmed last week                       10992
1 week change                               432
1 week % increase                          3.93
WHO Region                Eastern Mediterranean
Name: 159, dtype: object)
(160, Country/Region            Suriname
Confirmed                     1483
Deaths                          24
Recovered                      925
Active                         534
New cases                       44
New deaths                       1
New recovered                   35
Deaths / 100 Cases            1.62
Recovered / 100 Cases        62.37
Deaths / 100 Recovered        2.59
Confirmed last week           1079
1 week change                  404
1 week % increase            37.44
WHO Region                Americas
Name: 160, dtype: object)
(161, Country/Region            Sweden
Confirmed                  79395
Deaths                      5700
Recovered                      0
Active                     73695
New cases                    398
New deaths                     3
New recovered                  0
Deaths / 100 Cases          7.18
Recovered / 100 Cases          0
Deaths / 100 Recovered       inf
Confirmed last week        78048
1 week change               1347
1 week % increase           1.73
WHO Region                Europe
Name: 161, dtype: object)
(162, Country/Region            Switzerland
Confirmed                       34477
Deaths                           1978
Recovered                       30900
Active                           1599
New cases                          65
New deaths                          1
New recovered                     200
Deaths / 100 Cases               5.74
Recovered / 100 Cases           89.62
Deaths / 100 Recovered            6.4
Confirmed last week             33634
1 week change                     843
1 week % increase                2.51
WHO Region                     Europe
Name: 162, dtype: object)
(163, Country/Region                            Syria
Confirmed                                   674
Deaths                                       40
Recovered                                     0
Active                                      634
New cases                                    24
New deaths                                    2
New recovered                                 0
Deaths / 100 Cases                         5.93
Recovered / 100 Cases                         0
Deaths / 100 Recovered                      inf
Confirmed last week                         522
1 week change                               152
1 week % increase                         29.12
WHO Region                Eastern Mediterranean
Name: 163, dtype: object)
(164, Country/Region                    Taiwan*
Confirmed                             462
Deaths                                  7
Recovered                             440
Active                                 15
New cases                               4
New deaths                              0
New recovered                           0
Deaths / 100 Cases                   1.52
Recovered / 100 Cases               95.24
Deaths / 100 Recovered               1.59
Confirmed last week                   451
1 week change                          11
1 week % increase                    2.44
WHO Region                Western Pacific
Name: 164, dtype: object)
(165, Country/Region            Tajikistan
Confirmed                       7235
Deaths                            60
Recovered                       6028
Active                          1147
New cases                         43
New deaths                         1
New recovered                     58
Deaths / 100 Cases              0.83
Recovered / 100 Cases          83.32
Deaths / 100 Recovered             1
Confirmed last week             6921
1 week change                    314
1 week % increase               4.54
WHO Region                    Europe
Name: 165, dtype: object)
(166, Country/Region            Tanzania
Confirmed                      509
Deaths                          21
Recovered                      183
Active                         305
New cases                        0
New deaths                       0
New recovered                    0
Deaths / 100 Cases            4.13
Recovered / 100 Cases        35.95
Deaths / 100 Recovered       11.48
Confirmed last week            509
1 week change                    0
1 week % increase                0
WHO Region                  Africa
Name: 166, dtype: object)
(167, Country/Region                   Thailand
Confirmed                            3297
Deaths                                 58
Recovered                            3111
Active                                128
New cases                               6
New deaths                              0
New recovered                           2
Deaths / 100 Cases                   1.76
Recovered / 100 Cases               94.36
Deaths / 100 Recovered               1.86
Confirmed last week                  3250
1 week change                          47
1 week % increase                    1.45
WHO Region                South-East Asia
Name: 167, dtype: object)
(168, Country/Region                Timor-Leste
Confirmed                              24
Deaths                                  0
Recovered                               0
Active                                 24
New cases                               0
New deaths                              0
New recovered                           0
Deaths / 100 Cases                      0
Recovered / 100 Cases                   0
Deaths / 100 Recovered                  0
Confirmed last week                    24
1 week change                           0
1 week % increase                       0
WHO Region                South-East Asia
Name: 168, dtype: object)
(169, Country/Region              Togo
Confirmed                    874
Deaths                        18
Recovered                    607
Active                       249
New cases                      6
New deaths                     0
New recovered                  8
Deaths / 100 Cases          2.06
Recovered / 100 Cases      69.45
Deaths / 100 Recovered      2.97
Confirmed last week          783
1 week change                 91
1 week % increase          11.62
WHO Region                Africa
Name: 169, dtype: object)
(170, Country/Region            Trinidad and Tobago
Confirmed                                 148
Deaths                                      8
Recovered                                 128
Active                                     12
New cases                                   1
New deaths                                  0
New recovered                               0
Deaths / 100 Cases                       5.41
Recovered / 100 Cases                   86.49
Deaths / 100 Recovered                   6.25
Confirmed last week                       137
1 week change                              11
1 week % increase                        8.03
WHO Region                           Americas
Name: 170, dtype: object)
(171, Country/Region                          Tunisia
Confirmed                                  1455
Deaths                                       50
Recovered                                  1157
Active                                      248
New cases                                     3
New deaths                                    0
New recovered                                15
Deaths / 100 Cases                         3.44
Recovered / 100 Cases                     79.52
Deaths / 100 Recovered                     4.32
Confirmed last week                        1381
1 week change                                74
1 week % increase                          5.36
WHO Region                Eastern Mediterranean
Name: 171, dtype: object)
(172, Country/Region            Turkey
Confirmed                 227019
Deaths                      5630
Recovered                 210469
Active                     10920
New cases                    919
New deaths                    17
New recovered                982
Deaths / 100 Cases          2.48
Recovered / 100 Cases      92.71
Deaths / 100 Recovered      2.67
Confirmed last week       220572
1 week change               6447
1 week % increase           2.92
WHO Region                Europe
Name: 172, dtype: object)
(173, Country/Region                  US
Confirmed                  4290259
Deaths                      148011
Recovered                  1325804
Active                     2816444
New cases                    56336
New deaths                    1076
New recovered                27941
Deaths / 100 Cases            3.45
Recovered / 100 Cases         30.9
Deaths / 100 Recovered       11.16
Confirmed last week        3834677
1 week change               455582
1 week % increase            11.88
WHO Region                Americas
Name: 173, dtype: object)
(174, Country/Region            Uganda
Confirmed                   1128
Deaths                         2
Recovered                    986
Active                       140
New cases                     13
New deaths                     0
New recovered                  4
Deaths / 100 Cases          0.18
Recovered / 100 Cases      87.41
Deaths / 100 Recovered       0.2
Confirmed last week         1069
1 week change                 59
1 week % increase           5.52
WHO Region                Africa
Name: 174, dtype: object)
(175, Country/Region            Ukraine
Confirmed                   67096
Deaths                       1636
Recovered                   37202
Active                      28258
New cases                     835
New deaths                     11
New recovered                 317
Deaths / 100 Cases           2.44
Recovered / 100 Cases       55.45
Deaths / 100 Recovered        4.4
Confirmed last week         60767
1 week change                6329
1 week % increase           10.42
WHO Region                 Europe
Name: 175, dtype: object)
(176, Country/Region             United Arab Emirates
Confirmed                                 59177
Deaths                                      345
Recovered                                 52510
Active                                     6322
New cases                                   264
New deaths                                    1
New recovered                               328
Deaths / 100 Cases                         0.58
Recovered / 100 Cases                     88.73
Deaths / 100 Recovered                     0.66
Confirmed last week                       57193
1 week change                              1984
1 week % increase                          3.47
WHO Region                Eastern Mediterranean
Name: 176, dtype: object)
(177, Country/Region            United Kingdom
Confirmed                         301708
Deaths                             45844
Recovered                           1437
Active                            254427
New cases                            688
New deaths                             7
New recovered                          3
Deaths / 100 Cases                 15.19
Recovered / 100 Cases               0.48
Deaths / 100 Recovered           3190.26
Confirmed last week               296944
1 week change                       4764
1 week % increase                    1.6
WHO Region                        Europe
Name: 177, dtype: object)
(178, Country/Region             Uruguay
Confirmed                     1202
Deaths                          35
Recovered                      951
Active                         216
New cases                       10
New deaths                       1
New recovered                    3
Deaths / 100 Cases            2.91
Recovered / 100 Cases        79.12
Deaths / 100 Recovered        3.68
Confirmed last week           1064
1 week change                  138
1 week % increase            12.97
WHO Region                Americas
Name: 178, dtype: object)
(179, Country/Region            Uzbekistan
Confirmed                      21209
Deaths                           121
Recovered                      11674
Active                          9414
New cases                        678
New deaths                         5
New recovered                    569
Deaths / 100 Cases              0.57
Recovered / 100 Cases          55.04
Deaths / 100 Recovered          1.04
Confirmed last week            17149
1 week change                   4060
1 week % increase              23.67
WHO Region                    Europe
Name: 179, dtype: object)
(180, Country/Region            Venezuela
Confirmed                     15988
Deaths                          146
Recovered                      9959
Active                         5883
New cases                       525
New deaths                        4
New recovered                   213
Deaths / 100 Cases             0.91
Recovered / 100 Cases         62.29
Deaths / 100 Recovered         1.47
Confirmed last week           12334
1 week change                  3654
1 week % increase             29.63
WHO Region                 Americas
Name: 180, dtype: object)
(181, Country/Region                    Vietnam
Confirmed                             431
Deaths                                  0
Recovered                             365
Active                                 66
New cases                              11
New deaths                              0
New recovered                           0
Deaths / 100 Cases                      0
Recovered / 100 Cases               84.69
Deaths / 100 Recovered                  0
Confirmed last week                   384
1 week change                          47
1 week % increase                   12.24
WHO Region                Western Pacific
Name: 181, dtype: object)
(182, Country/Region               West Bank and Gaza
Confirmed                                 10621
Deaths                                       78
Recovered                                  3752
Active                                     6791
New cases                                   152
New deaths                                    2
New recovered                                 0
Deaths / 100 Cases                         0.73
Recovered / 100 Cases                     35.33
Deaths / 100 Recovered                     2.08
Confirmed last week                        8916
1 week change                              1705
1 week % increase                         19.12
WHO Region                Eastern Mediterranean
Name: 182, dtype: object)
(183, Country/Region            Western Sahara
Confirmed                             10
Deaths                                 1
Recovered                              8
Active                                 1
New cases                              0
New deaths                             0
New recovered                          0
Deaths / 100 Cases                    10
Recovered / 100 Cases                 80
Deaths / 100 Recovered              12.5
Confirmed last week                   10
1 week change                          0
1 week % increase                      0
WHO Region                        Africa
Name: 183, dtype: object)
(184, Country/Region                            Yemen
Confirmed                                  1691
Deaths                                      483
Recovered                                   833
Active                                      375
New cases                                    10
New deaths                                    4
New recovered                                36
Deaths / 100 Cases                        28.56
Recovered / 100 Cases                     49.26
Deaths / 100 Recovered                    57.98
Confirmed last week                        1619
1 week change                                72
1 week % increase                          4.45
WHO Region                Eastern Mediterranean
Name: 184, dtype: object)
(185, Country/Region            Zambia
Confirmed                   4552
Deaths                       140
Recovered                   2815
Active                      1597
New cases                     71
New deaths                     1
New recovered                465
Deaths / 100 Cases          3.08
Recovered / 100 Cases      61.84
Deaths / 100 Recovered      4.97
Confirmed last week         3326
1 week change               1226
1 week % increase          36.86
WHO Region                Africa
Name: 185, dtype: object)
(186, Country/Region            Zimbabwe
Confirmed                     2704
Deaths                          36
Recovered                      542
Active                        2126
New cases                      192
New deaths                       2
New recovered                   24
Deaths / 100 Cases            1.33
Recovered / 100 Cases        20.04
Deaths / 100 Recovered        6.64
Confirmed last week           1713
1 week change                  991
1 week % increase            57.85
WHO Region                  Africa
Name: 186, dtype: object)

In [30]:
for i,row in covid.iterrows():
    while i <3:
        print(f'i={i}')
        break

i=0
i=1
i=2

In [31]:
for i,row in covid.iterrows():
    while i <3:
        print(f'i={i}')
        print('')
        break

i=0

i=1

i=2

In [32]:
for i,row in covid.iterrows():
    while i <3:
        print(f'i={i}')
        print('')
        print('Return Row:')
        break

i=0

Return Row:
i=1

Return Row:
i=2

Return Row:

In [33]:
for i,row in covid.iterrows():
    while i <3:
        print(f'i={i}')
        print('')
        print('Return Row:')
        print(row)
        break

i=0

Return Row:
Country/Region                      Afghanistan
Confirmed                                 36263
Deaths                                     1269
Recovered                                 25198
Active                                     9796
New cases                                   106
New deaths                                   10
New recovered                                18
Deaths / 100 Cases                          3.5
Recovered / 100 Cases                     69.49
Deaths / 100 Recovered                     5.04
Confirmed last week                       35526
1 week change                               737
1 week % increase                          2.07
WHO Region                Eastern Mediterranean
Name: 0, dtype: object
i=1

Return Row:
Country/Region            Albania
Confirmed                    4880
Deaths                        144
Recovered                    2745
Active                       1991
New cases                     117
New deaths                      6
New recovered                  63
Deaths / 100 Cases           2.95
Recovered / 100 Cases       56.25
Deaths / 100 Recovered       5.25
Confirmed last week          4171
1 week change                 709
1 week % increase              17
WHO Region                 Europe
Name: 1, dtype: object
i=2

Return Row:
Country/Region            Algeria
Confirmed                   27973
Deaths                       1163
Recovered                   18837
Active                       7973
New cases                     616
New deaths                      8
New recovered                 749
Deaths / 100 Cases           4.16
Recovered / 100 Cases       67.34
Deaths / 100 Recovered       6.17
Confirmed last week         23691
1 week change                4282
1 week % increase           18.07
WHO Region                 Africa
Name: 2, dtype: object

In [34]:
for i,row in covid.iterrows():
    while i <3:
        print(f'i={i}')
        print('')
        print('Return Row:')
        print(row)
        print('')
        break

i=0

Return Row:
Country/Region                      Afghanistan
Confirmed                                 36263
Deaths                                     1269
Recovered                                 25198
Active                                     9796
New cases                                   106
New deaths                                   10
New recovered                                18
Deaths / 100 Cases                          3.5
Recovered / 100 Cases                     69.49
Deaths / 100 Recovered                     5.04
Confirmed last week                       35526
1 week change                               737
1 week % increase                          2.07
WHO Region                Eastern Mediterranean
Name: 0, dtype: object

i=1

Return Row:
Country/Region            Albania
Confirmed                    4880
Deaths                        144
Recovered                    2745
Active                       1991
New cases                     117
New deaths                      6
New recovered                  63
Deaths / 100 Cases           2.95
Recovered / 100 Cases       56.25
Deaths / 100 Recovered       5.25
Confirmed last week          4171
1 week change                 709
1 week % increase              17
WHO Region                 Europe
Name: 1, dtype: object

i=2

Return Row:
Country/Region            Algeria
Confirmed                   27973
Deaths                       1163
Recovered                   18837
Active                       7973
New cases                     616
New deaths                      8
New recovered                 749
Deaths / 100 Cases           4.16
Recovered / 100 Cases       67.34
Deaths / 100 Recovered       6.17
Confirmed last week         23691
1 week change                4282
1 week % increase           18.07
WHO Region                 Africa
Name: 2, dtype: object

In [35]:
for i,row in covid.iterrows():
    while i <3:
        print(f'i={i}')
        print('')
        print('Return Row:')
        print(row)
        print('')
        print(f"column Country/Region: { row ['Country/Region']}")
        break

i=0

Return Row:
Country/Region                      Afghanistan
Confirmed                                 36263
Deaths                                     1269
Recovered                                 25198
Active                                     9796
New cases                                   106
New deaths                                   10
New recovered                                18
Deaths / 100 Cases                          3.5
Recovered / 100 Cases                     69.49
Deaths / 100 Recovered                     5.04
Confirmed last week                       35526
1 week change                               737
1 week % increase                          2.07
WHO Region                Eastern Mediterranean
Name: 0, dtype: object

column Country/Region: Afghanistan
i=1

Return Row:
Country/Region            Albania
Confirmed                    4880
Deaths                        144
Recovered                    2745
Active                       1991
New cases                     117
New deaths                      6
New recovered                  63
Deaths / 100 Cases           2.95
Recovered / 100 Cases       56.25
Deaths / 100 Recovered       5.25
Confirmed last week          4171
1 week change                 709
1 week % increase              17
WHO Region                 Europe
Name: 1, dtype: object

column Country/Region: Albania
i=2

Return Row:
Country/Region            Algeria
Confirmed                   27973
Deaths                       1163
Recovered                   18837
Active                       7973
New cases                     616
New deaths                      8
New recovered                 749
Deaths / 100 Cases           4.16
Recovered / 100 Cases       67.34
Deaths / 100 Recovered       6.17
Confirmed last week         23691
1 week change                4282
1 week % increase           18.07
WHO Region                 Africa
Name: 2, dtype: object

column Country/Region: Algeria

In [36]:
for i,row in covid.iterrows():
    while i <3:
        print(f'i={i}')
        print('')
        print('Return Row:')
        print(row)
        print('')
        print(f"column Country/Region: { row ['Country/Region']}")
        print("<-------------------------------------------------->")
        print('')
        break

i=0

Return Row:
Country/Region                      Afghanistan
Confirmed                                 36263
Deaths                                     1269
Recovered                                 25198
Active                                     9796
New cases                                   106
New deaths                                   10
New recovered                                18
Deaths / 100 Cases                          3.5
Recovered / 100 Cases                     69.49
Deaths / 100 Recovered                     5.04
Confirmed last week                       35526
1 week change                               737
1 week % increase                          2.07
WHO Region                Eastern Mediterranean
Name: 0, dtype: object

column Country/Region: Afghanistan
<-------------------------------------------------->

i=1

Return Row:
Country/Region            Albania
Confirmed                    4880
Deaths                        144
Recovered                    2745
Active                       1991
New cases                     117
New deaths                      6
New recovered                  63
Deaths / 100 Cases           2.95
Recovered / 100 Cases       56.25
Deaths / 100 Recovered       5.25
Confirmed last week          4171
1 week change                 709
1 week % increase              17
WHO Region                 Europe
Name: 1, dtype: object

column Country/Region: Albania
<-------------------------------------------------->

i=2

Return Row:
Country/Region            Algeria
Confirmed                   27973
Deaths                       1163
Recovered                   18837
Active                       7973
New cases                     616
New deaths                      8
New recovered                 749
Deaths / 100 Cases           4.16
Recovered / 100 Cases       67.34
Deaths / 100 Recovered       6.17
Confirmed last week         23691
1 week change                4282
1 week % increase           18.07
WHO Region                 Africa
Name: 2, dtype: object

column Country/Region: Algeria
<-------------------------------------------------->